### ISSUE TITLE
Download scheitert bei Umlauten

### ISSUE THREAD

**Issue by vitusson** [YeaSoft/plugin.video.mediathekview#6]
Mein erster Download läuft gerade, erfolgreich.
Aber der allererste Versuch ging schief, weil ich ausgerechnet eine Sendung mit Umlaut ausgesucht hatte.
ß im Namen geht auch nicht.

```
00:52:20.539 T:1111913376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe4' in position 31: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 323, in <module>
                                                addon.Do()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 312, in Do
                                                self.doDownloadFilm( self.args.get( 'id', [0] )[0] )
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 187, in doDownloadFilm
                                                if os.path.isfile( movname ):
                                              File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 31: ordinal not in range(128)
                                            -->End of Python script error report<--
```

Aktuelles LibreELEC. RPi3

**Comment by domschl** [comment]
Look at: http://kodi.wiki/view/Add-on_unicode_paths
